default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD', '') %>
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>

development:
  <<: *default
  database: rails_on_github_actions_development
test:
  <<: *default
  database: rails_on_github_actions_test
production:
  <<: *default
  database: rails_on_github_actions_production