name: Rails

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
    container:
      image: ruby:2.6.3
      env:
        MYSQL_HOST: mysql
        MYSQL_ROOT_PASSWORD: password

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
    - name: Set up rails
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with rspec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
        bundle exec rspec
